name: Build Docker Images

on: push

env:
  QT_MAJOR: "515"
  QT_VERSION: "5.15.0"

jobs:
  qtcreator-clang:
    name: "QtCreator + Clang"
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: focal
            clang_major: 12
            qtcreator: 4.15.0
            QT_CREATOR_URL: "https://github.com/arBmind/qt-creator/releases/download/v4.15.0-rc1-patched-snapshot-2021-05-02/qtcreator-Linux-803135866.7z"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: QtCreator ${{ env.qtcreator }} + Clang${{ matrix.clang_major }}
        uses: docker/build-push-action@v2
        with:
          target: qtcreator-clang-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-clang:latest
            arbmind/qtcreator-clang:${{ matrix.qtcreator }}-${{ matrix.clang_major }}
          build_args: |
            DISTRO=${{ matrix.distro }}
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_MAJOR=${{ env.QT_MAJOR }}
            QT_VERSION=${{ env.QT_VERSION }}
            QT_CREATOR_URL=${{ matrix.QT_CREATOR_URL }}
