name: Build Docker Images

on: push

jobs:
  qtcreator-clang:
    name: "QtCreator"
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: focal
            gcc_major: 11
            clang_major: 14
            qtcreator: 7.0.1-patched
            qtcreator_url: "https://github.com/arBmind/qt-creator/releases/download/v7.0.1-patched-snapshot-2022-04-02/qtcreator-Linux-2083095478.7z"
            qt_version: 6.3.0
            clang_tags: arbmind/qtcreator-clang:latest
            clang_libstdcpp_tags: arbmind/qtcreator-clang-libstdcpp:latest
            clang_libstdcpp_qt_tags: arbmind/qtcreator-clang-libstdcpp-qt:latest
            gcc_tags: arbmind/qtcreator-gcc:latest
            gcc_qt_tags: arbmind/qtcreator-gcc-qt:latest

          - distro: focal
            gcc_major: 11
            clang_major: 13
            qtcreator: 7.0.1-patched
            qtcreator_url: "https://github.com/arBmind/qt-creator/releases/download/v7.0.1-patched-snapshot-2022-04-02/qtcreator-Linux-2083095478.7z"
            qt_version: 6.3.0

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: QtCreator ${{ matrix.qtcreator }} + Clang${{ matrix.clang_major }}
        uses: docker/build-push-action@v2
        with:
          target: qtcreator-clang
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-clang:${{ matrix.qtcreator }}-${{ matrix.clang_major }}
            ${{ matrix.clang_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_CREATOR_VERSION=${{ matrix.qtcreator }}
            QTCREATOR_URL=${{ matrix.qtcreator_url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator }}

      - name: QtCreator ${{ matrix.qtcreator }} + Clang${{ matrix.clang_major }} + libstdc++-${{ matrix.gcc_major }}
        uses: docker/build-push-action@v2
        with:
          target: qtcreator-clang-libstdcpp
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-clang-libstdcpp:${{ matrix.qtcreator }}-${{ matrix.clang_major }}-${{ matrix.gcc_major }}
            ${{ matrix.clang_libstdcpp_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_VERSION=${{ matrix.qt_version }}
            QTCREATOR_URL=${{ matrix.qtcreator_url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator }}

      - name: QtCreator ${{ matrix.qtcreator }} + Clang${{ matrix.clang_major }} + libstdc++-${{ matrix.gcc_major }} + Qt-${{ matrix.qt_version }}
        uses: docker/build-push-action@v2
        with:
          target: qtcreator-clang-libstdcpp-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-clang-libstdcpp-qt:${{ matrix.qtcreator }}-${{ matrix.clang_major }}-${{ matrix.gcc_major }}-${{ matrix.qt_version }}
            ${{ matrix.clang_libstdcpp_qt_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_VERSION=${{ matrix.qt_version }}
            QTCREATOR_URL=${{ matrix.qtcreator_url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator }}

      - name: QtCreator ${{ matrix.qtcreator }} + GCC${{ matrix.gcc_major }}
        uses: docker/build-push-action@v2
        with:
          target: qtcreator-gcc
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-gcc:${{ matrix.qtcreator }}-${{ matrix.gcc_major }}
            ${{ matrix.gcc_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_VERSION=${{ matrix.qt_version }}
            QTCREATOR_URL=${{ matrix.qtcreator_url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator }}

      - name: QtCreator ${{ matrix.qtcreator }} + GCC${{ matrix.gcc_major }} + Qt-${{ matrix.qt_version }}
        uses: docker/build-push-action@v2
        with:
          target: qtcreator-gcc-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-gcc-qt:${{ matrix.qtcreator }}-${{ matrix.gcc_major }}-${{ matrix.qt_version }}
            ${{ matrix.gcc_qt_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_VERSION=${{ matrix.qt_version }}
            QTCREATOR_URL=${{ matrix.qtcreator_url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator }}
